-- 材料库（192 种）
insert into ingredients (id, name, cat, emoji, aka, alias, is_basic, py, initial) values
('gin', '金酒（琴酒）', '基酒', '🌿', 'Gin', '琴酒 / 毡酒 / 杜松子酒 / Geneva', false, 'jinjiuqinjiu', 'J'),
('vodka', '伏特加', '基酒', '💧', 'Vodka', '伏特卡 / 俄得克 / 火酒', false, 'futejia', 'F'),
('white-rum', '白朗姆酒', '基酒', '🏝️', 'White Rum', '朗姆酒 / 兰姆酒 / 白朗姆 / 蔗酒', false, 'bailangmujiu', 'B'),
('dark-rum', '黑朗姆酒', '基酒', '🪵', 'Dark Rum', '黑朗姆 / 深色朗姆酒', false, 'heilangmujiu', 'H'),
('tequila', '龙舌兰', '基酒', '🌵', 'Tequila', '特基拉 / 龙舌兰酒', false, 'longshelan', 'L'),
('mezcal', '梅斯卡尔', '基酒', '🔥', 'Mezcal', '龙舌兰酒 / 麦斯卡尔', false, 'meisikaer', 'M'),
('bourbon', '波本威士忌', '基酒', '🥃', 'Bourbon', '波本 / 波本酒', false, 'bobenweishiji', 'B'),
('rye', '黑麦威士忌', '基酒', '🌾', 'Rye Whiskey', '裸麦威士忌 / 黑麦酒', false, 'heimaiweishiji', 'H'),
('scotch', '苏格兰威士忌', '基酒', '🏴', 'Scotch', '苏威 / 苏格兰酒 / 威士忌', false, 'sugelanweishiji', 'S'),
('brandy', '白兰地', '基酒', '🍇', 'Brandy', '白兰地酒', false, 'bailandi', 'B'),
('cognac', '干邑', '基酒', '🥂', 'Cognac', '干邑白兰地 / 科涅克', false, 'ganyi', 'G'),
('cachaca', '卡莎萨', '基酒', '🇧🇷', 'Cachaça', '', false, 'kashasa', 'K'),
('sparkling', '气泡酒 / 香槟', '基酒', '🍾', 'Sparkling Wine', '香槟 / 起泡酒 / 气泡酒', false, 'qipaojiuxiangbin', 'Q'),
('sake', '清酒', '基酒', '🍶', 'Sake', '日本酒 / 清酒', false, 'qingjiu', 'Q'),
('soju', '烧酒', '基酒', '🍶', 'Soju', '', false, 'shaojiu', 'S'),
('baijiu', '白酒', '基酒', '🏮', 'Baijiu', '高粱酒 / 中国白酒', false, 'baijiu', 'B'),
('golden-rum', '金朗姆酒', '基酒', '🥇', 'Golden Rum', '', false, 'jinlangmujiu', 'J'),
('aged-rum', '陈年朗姆酒', '基酒', '🛢️', 'Aged Rum', '', false, 'chennianlangmujiu', 'C'),
('overproof-rum', '高度朗姆 151', '基酒', '🔥', 'Overproof Rum', '', false, 'gaodulangmu151', 'G'),
('pisco', '皮斯科', '基酒', '🍇', 'Pisco', '', false, 'pisike', 'P'),
('armagnac', '雅文邑', '基酒', '🍇', 'Armagnac', '', false, 'yawenyi', 'Y'),
('canadian-whisky', '加拿大威士忌', '基酒', '🍁', 'Canadian Whisky', '', false, 'jianadaweishiji', 'J'),
('japanese-whisky', '日本威士忌', '基酒', '🗾', 'Japanese Whisky', '', false, 'ribenweishiji', 'R'),
('irish-whiskey', '爱尔兰威士忌', '基酒', '🍀', 'Irish Whiskey', '', false, 'aierlanweishiji', 'A'),
('sherry', '雪莉酒', '基酒', '🍷', 'Sherry', '', false, 'xuelijiu', 'X'),
('port', '波特酒', '基酒', '🍷', 'Port', '', false, 'botejiu', 'B'),
('red-wine', '红葡萄酒', '基酒', '🍷', 'Red Wine', '', false, 'hongputaojiu', 'H'),
('white-wine', '白葡萄酒', '基酒', '🥂', 'White Wine', '', false, 'baiputaojiu', 'B'),
('plum-wine', '梅酒', '基酒', '🫐', 'Umeshu', '', false, 'meijiu', 'M'),
('rice-wine', '黄酒 / 米酒', '基酒', '🍚', 'Rice Wine', '', false, 'huangjiumijiu', 'H'),
('applejack', '苹果白兰地', '基酒', '🍎', 'Applejack', '', false, 'pingguobailandi', 'P'),
('calvados', '卡尔瓦多斯', '基酒', '🍏', 'Calvados / 苹果白兰地', '', false, 'kaerwaduosi', 'K'),
('tennessee-whiskey', '田纳西威士忌', '基酒', '🎸', 'Tennessee Whiskey', '', false, 'tiannaxiweishiji', 'T'),
('single-malt', '单一麦芽威士忌', '基酒', '🥃', 'Single Malt', '', false, 'danyimaiyaweishiji', 'D'),
('reposado', '陈酿龙舌兰', '基酒', '🌵', 'Reposado / 微陈龙舌兰', '', false, 'chennianglongshelan', 'C'),
('anejo', '陈年龙舌兰', '基酒', '🛢️', 'Añejo', '', false, 'chennianlongshelan', 'C'),
('madeira', '马德拉酒', '基酒', '🍷', 'Madeira', '', false, 'madelajiu', 'M'),
('cointreau', '君度橙酒', '利口酒', '🍊', 'Cointreau', '柑香酒 / 橙皮甜酒', false, 'junduchengjiu', 'J'),
('triple-sec', '白橙皮利口酒', '利口酒', '🍊', 'Triple Sec', '三重橙 / 白橙皮酒', false, 'baichengpilikoujiu', 'B'),
('campari', '金巴利', '利口酒', '❤️', 'Campari', '金巴丽 / 康帕利', false, 'jinbali', 'J'),
('aperol', '阿佩罗', '利口酒', '🧡', 'Aperol', '艾普罗 / 开胃酒', false, 'apeiluo', 'A'),
('sweet-vermouth', '甜味美思', '利口酒', '🍷', 'Sweet Vermouth', '甜苦艾酒 / 红味美思 / 意大利味美思', false, 'tianweimeisi', 'T'),
('dry-vermouth', '干味美思', '利口酒', '🥂', 'Dry Vermouth', '干苦艾酒 / 白味美思 / 法式味美思', false, 'ganweimeisi', 'G'),
('kahlua', '咖啡利口酒', '利口酒', '☕', 'Kahlúa', '甘露 / 卡鲁哇 / 咖啡香甜酒', false, 'kafeilikoujiu', 'K'),
('baileys', '百利甜酒', '利口酒', '🥛', 'Baileys', '百利甜 / 爱尔兰奶油酒', false, 'bailitianjiu', 'B'),
('amaretto', '杏仁利口酒', '利口酒', '🌰', 'Amaretto', '阿玛雷托 / 杏仁酒', false, 'xingrenlikoujiu', 'X'),
('blue-curacao', '蓝橙利口酒', '利口酒', '💙', 'Blue Curaçao', '蓝橙酒 / 蓝柑香酒', false, 'lanchenglikoujiu', 'L'),
('peach', '蜜桃利口酒', '利口酒', '🍑', 'Peach Schnapps', '', false, 'mitaolikoujiu', 'M'),
('cacao-white', '白可可利口酒', '利口酒', '🍫', 'Crème de Cacao', '', false, 'baikekelikoujiu', 'B'),
('st-germain', '接骨木花利口酒', '利口酒', '🌸', 'St-Germain', '圣杰曼 / 接骨木花酒', false, 'jiegumuhualikoujiu', 'J'),
('midori', '蜜多丽蜜瓜酒', '利口酒', '🍈', 'Midori', '蜜瓜酒 / 美多丽', false, 'miduolimiguajiu', 'M'),
('malibu', '椰香朗姆酒', '利口酒', '🥥', 'Malibu', '马利宝 / 椰香朗姆', false, 'yexianglangmujiu', 'Y'),
('absinthe', '苦艾酒', '利口酒', '🧚', 'Absinthe', '苦艾酒 / 艾碧斯 / 绿仙子', false, 'kuaijiu', 'K'),
('grand-marnier', '柑曼怡', '利口酒', '🍊', 'Grand Marnier', '', false, 'ganmanyi', 'G'),
('maraschino', '黑樱桃利口酒', '利口酒', '🍒', 'Maraschino', '', false, 'heiyingtaolikoujiu', 'H'),
('chambord', '香波黑莓利口酒', '利口酒', '🫐', 'Chambord', '', false, 'xiangboheimeilikoujiu', 'X'),
('chartreuse', '荨麻酒（绿）', '利口酒', '🌿', 'Chartreuse', '', false, 'qianmajiul', 'Q'),
('benedictine', '廊酒', '利口酒', '🏛️', 'Bénédictine', '', false, 'langjiu', 'L'),
('drambuie', '杜林标', '利口酒', '🥃', 'Drambuie', '', false, 'dulinbiao', 'D'),
('frangelico', '榛子利口酒', '利口酒', '🌰', 'Frangelico', '', false, 'zhenzilikoujiu', 'Z'),
('banana-liqueur', '香蕉利口酒', '利口酒', '🍌', 'Crème de Banane', '', false, 'xiangjiaolikoujiu', 'X'),
('vanilla-liqueur', '香草利口酒', '利口酒', '🍦', 'Vanilla Liqueur', '', false, 'xiangcaolikoujiu', 'X'),
('galliano', '加利安奴', '利口酒', '🍮', 'Galliano', '', false, 'jialiannu', 'J'),
('creme-de-menthe', '薄荷利口酒', '利口酒', '🌱', 'Crème de Menthe', '', false, 'bohelikoujiu', 'B'),
('creme-de-cacao-dark', '深色可可利口酒', '利口酒', '🍫', 'Dark Crème de Cacao', '', false, 'shensekekelikoujiu', 'S'),
('creme-de-violette', '紫罗兰利口酒', '利口酒', '💜', 'Crème de Violette', '', false, 'ziluolanlikoujiu', 'Z'),
('pimms', '皮姆酒', '利口酒', '🍓', 'Pimm''s', '', false, 'pimujiu', 'P'),
('limoncello', '柠檬切罗', '利口酒', '🍋', 'Limoncello', '', false, 'ningmengqieluo', 'N'),
('lillet', '利莱白', '利口酒', '🍾', 'Lillet Blanc', '', false, 'lilaibai', 'L'),
('amaro', '阿玛罗苦酒', '利口酒', '🥀', 'Amaro', '', false, 'amaluokujiu', 'A'),
('creme-de-cassis', '黑加仑利口酒', '利口酒', '🫐', 'Crème de Cassis / 黑醋栗', '黑醋栗利口酒 / 卡西斯', false, 'heijialunlikoujiu', 'H'),
('blueberry-liqueur', '蓝莓利口酒', '利口酒', '🫐', 'Blueberry Liqueur', '', false, 'lanmeilikoujiu', 'L'),
('lychee-liqueur', '荔枝利口酒', '利口酒', '🫒', 'Lychee Liqueur', '', false, 'lizhilikoujiu', 'L'),
('rose-liqueur', '玫瑰利口酒', '利口酒', '🌹', 'Rose Liqueur', '', false, 'meiguilikoujiu', 'M'),
('lime-juice', '青柠汁', '果汁与饮料', '🟢', 'Lime Juice', '莱姆汁', false, 'qingningzhi', 'Q'),
('lemon-juice', '柠檬汁', '果汁与饮料', '🟡', 'Lemon Juice', '', false, 'ningmengzhi', 'N'),
('orange-juice', '橙汁', '果汁与饮料', '🍊', 'Orange Juice', '', false, 'chengzhi', 'C'),
('pineapple-juice', '菠萝汁', '果汁与饮料', '🍍', 'Pineapple Juice', '', false, 'boluozhi', 'B'),
('cranberry-juice', '蔓越莓汁', '果汁与饮料', '🍒', 'Cranberry Juice', '', false, 'manyuemeizhi', 'M'),
('grapefruit-juice', '西柚汁', '果汁与饮料', '🍊', 'Grapefruit Juice', '', false, 'xiyouzhi', 'X'),
('tomato-juice', '番茄汁', '果汁与饮料', '🍅', 'Tomato Juice', '', false, 'fanqiezhi', 'F'),
('coconut-cream', '椰浆', '果汁与饮料', '🥥', 'Coconut Cream', '', false, 'yejiang', 'Y'),
('tonic', '汤力水', '果汁与饮料', '🫧', 'Tonic Water', '通宁水 / 汤力汽水 / 奎宁水', false, 'tanglishui', 'T'),
('soda-water', '苏打水', '果汁与饮料', '💦', 'Soda Water', '苏打汽水 / 气泡水', false, 'sudashui', 'S'),
('cola', '可乐', '果汁与饮料', '🥤', 'Cola', '', false, 'kele', 'K'),
('sprite', '雪碧 / 七喜', '果汁与饮料', '🥤', 'Sprite', '', false, 'xuebiqixi', 'X'),
('ginger-beer', '姜汁啤酒', '果汁与饮料', '🫚', 'Ginger Beer', '', false, 'jiangzhipijiu', 'J'),
('espresso', '浓缩咖啡', '果汁与饮料', '☕', 'Espresso', '', false, 'nongsuokafei', 'N'),
('milk', '牛奶', '果汁与饮料', '🥛', 'Milk', '牛乳', false, 'niunai', 'N'),
('cream', '淡奶油', '果汁与饮料', '🍦', 'Cream', '鲜奶油 / 淡奶油', false, 'dannaiyou', 'D'),
('condensed-milk', '炼乳', '果汁与饮料', '🥛', 'Condensed Milk', '', false, 'lianru', 'L'),
('coconut-water', '椰子水', '果汁与饮料', '🥥', 'Coconut Water', '', false, 'yezishui', 'Y'),
('passionfruit-juice', '百香果汁', '果汁与饮料', '🟠', 'Passion Fruit Juice', '', false, 'baixiangguozhi', 'B'),
('mango-juice', '芒果汁', '果汁与饮料', '🥭', 'Mango Juice', '', false, 'mangguozhi', 'M'),
('watermelon-juice', '西瓜汁', '果汁与饮料', '🍉', 'Watermelon Juice', '', false, 'xiguazhi', 'X'),
('apple-juice', '苹果汁', '果汁与饮料', '🍎', 'Apple Juice', '', false, 'pingguozhi', 'P'),
('grape-juice', '葡萄汁', '果汁与饮料', '🍇', 'Grape Juice', '', false, 'putaozhi', 'P'),
('peach-juice', '桃子汁', '果汁与饮料', '🍑', 'Peach Juice', '', false, 'taozizhi', 'T'),
('ginger-ale', '干姜水', '果汁与饮料', '🫚', 'Ginger Ale', '', false, 'ganjiangshui', 'G'),
('bitter-lemon', '苦柠水', '果汁与饮料', '🍋', 'Bitter Lemon', '', false, 'kuningshui', 'K'),
('sparkling-water', '气泡水', '果汁与饮料', '🫧', 'Sparkling Water', '', false, 'qipaoshui', 'Q'),
('beer', '啤酒', '果汁与饮料', '🍺', 'Beer', '', false, 'pijiu', 'P'),
('pomegranate-juice', '石榴汁', '果汁与饮料', '🔴', 'Pomegranate Juice', '', false, 'shiliuzhi', 'S'),
('pear-juice', '梨汁', '果汁与饮料', '🍐', 'Pear Juice', '', false, 'lizhi', 'L'),
('lemonade', '柠檬水', '果汁与饮料', '🍋', 'Lemonade', '柠檬汽水 / 柠檬水饮料', false, 'ningmengshui', 'N'),
('energy-drink', '能量饮料', '果汁与饮料', '⚡', 'Energy Drink / 红牛', '红牛 / 提神饮料', false, 'nengliangyinliao', 'N'),
('iced-tea', '冰红茶', '果汁与饮料', '🧋', 'Iced Tea', '', false, 'binghongcha', 'B'),
('cream-soda', '奶油苏打', '果汁与饮料', '🥤', 'Cream Soda', '', false, 'naiyousuda', 'N'),
('simple-syrup', '糖浆', '糖浆与调味', '🍯', 'Simple Syrup', '糖水 / 单糖浆', false, 'tangjiang', 'T'),
('grenadine', '红石榴糖浆', '糖浆与调味', '🔴', 'Grenadine', '石榴糖浆 / 红石榴汁', false, 'hongshiliutangjiang', 'H'),
('orgeat', '杏仁糖浆', '糖浆与调味', '🌰', 'Orgeat', '', false, 'xingrentangjiang', 'X'),
('honey', '蜂蜜', '糖浆与调味', '🐝', 'Honey', '', false, 'fengmi', 'F'),
('agave', '龙舌兰糖浆', '糖浆与调味', '🌵', 'Agave Syrup', '', false, 'longshelantangjiang', 'L'),
('angostura', '安格仕苦精', '糖浆与调味', '🧪', 'Angostura Bitters', '安高天娜 / 安古斯图拉 / 苦精', false, 'angeshikujing', 'A'),
('salt', '盐', '糖浆与调味', '🧂', 'Salt', '', false, 'yan', 'Y'),
('sugar', '白砂糖', '糖浆与调味', '🍬', 'Sugar', '', false, 'baishatang', 'B'),
('pepper', '黑胡椒', '糖浆与调味', '⚫', 'Pepper', '', false, 'heihujiao', 'H'),
('worcestershire', '伍斯特酱', '糖浆与调味', '🧴', 'Worcestershire', '', false, 'wusitejiang', 'W'),
('tabasco', '塔巴斯科辣酱', '糖浆与调味', '🌶️', 'Tabasco', '', false, 'tabasikelajiang', 'T'),
('egg-white', '蛋清', '糖浆与调味', '🥚', 'Egg White', '蛋白', false, 'danqing', 'D'),
('egg-yolk', '蛋黄', '糖浆与调味', '🍳', 'Egg Yolk', '', false, 'danhuang', 'D'),
('vanilla-syrup', '香草糖浆', '糖浆与调味', '🍦', 'Vanilla Syrup', '', false, 'xiangcaotangjiang', 'X'),
('ginger-syrup', '姜糖浆', '糖浆与调味', '🫚', 'Ginger Syrup', '', false, 'jiangtangjiang', 'J'),
('cinnamon-syrup', '肉桂糖浆', '糖浆与调味', '🪵', 'Cinnamon Syrup', '', false, 'rouguitangjiang', 'R'),
('caramel-syrup', '焦糖糖浆', '糖浆与调味', '🍯', 'Caramel Syrup', '', false, 'jiaotangtangjiang', 'J'),
('rose-syrup', '玫瑰糖浆', '糖浆与调味', '🌹', 'Rose Syrup', '', false, 'meiguitangjiang', 'M'),
('elderflower-syrup', '接骨木花糖浆', '糖浆与调味', '🌸', 'Elderflower Syrup', '', false, 'jiegumuhuatangjiang', 'J'),
('passionfruit-syrup', '百香果糖浆', '糖浆与调味', '🟠', 'Passion Fruit Syrup', '', false, 'baixiangguotangjiang', 'B'),
('lychee-syrup', '荔枝糖浆', '糖浆与调味', '🫒', 'Lychee Syrup', '', false, 'lizhitangjiang', 'L'),
('coconut-syrup', '椰子糖浆', '糖浆与调味', '🥥', 'Coconut Syrup', '', false, 'yezitangjiang', 'Y'),
('raspberry-syrup', '覆盆子糖浆', '糖浆与调味', '🫐', 'Raspberry Syrup', '', false, 'fupenzitangjiang', 'F'),
('orange-bitters', '橙味苦精', '糖浆与调味', '🍊', 'Orange Bitters', '', false, 'chengweikujing', 'C'),
('celery-bitters', '芹菜苦精', '糖浆与调味', '🥬', 'Celery Bitters', '', false, 'qincaikujing', 'Q'),
('cinnamon-powder', '肉桂粉', '糖浆与调味', '🪵', 'Cinnamon', '', false, 'rouguifen', 'R'),
('cocoa-powder', '可可粉', '糖浆与调味', '🍫', 'Cocoa Powder', '', false, 'kekefen', 'K'),
('vanilla-extract', '香草精', '糖浆与调味', '🌼', 'Vanilla Extract', '', false, 'xiangcaojing', 'X'),
('clove', '丁香', '糖浆与调味', '🟤', 'Clove', '', false, 'dingxiang', 'D'),
('chili', '辣椒', '糖浆与调味', '🌶️', 'Chili', '', false, 'lajiao', 'L'),
('maple-syrup', '枫糖浆', '糖浆与调味', '🍁', 'Maple Syrup', '', false, 'fengtangjiang', 'F'),
('chocolate-bitters', '巧克力苦精', '糖浆与调味', '🍫', 'Chocolate Bitters', '', false, 'qiaokelikujing', 'Q'),
('celery-salt', '芹菜盐', '糖浆与调味', '🥬', 'Celery Salt', '', false, 'qincaiyan', 'Q'),
('orange-blossom', '橙花水', '糖浆与调味', '🌼', 'Orange Blossom Water', '', false, 'chenghuashui', 'C'),
('lime', '青柠', '新鲜水果', '🍋‍🟩', 'Lime', '莱姆', false, 'qingning', 'Q'),
('lemon', '柠檬', '新鲜水果', '🍋', 'Lemon', '', false, 'ningmeng', 'N'),
('orange', '橙子', '新鲜水果', '🍊', 'Orange', '甜橙', false, 'chengzi', 'C'),
('grapefruit', '西柚', '新鲜水果', '🍊', 'Grapefruit', '葡萄柚', false, 'xiyou', 'X'),
('strawberry', '草莓', '新鲜水果', '🍓', 'Strawberry', '士多啤梨', false, 'caomei', 'C'),
('pineapple', '菠萝', '新鲜水果', '🍍', 'Pineapple', '凤梨', false, 'boluo', 'B'),
('cherry', '樱桃', '新鲜水果', '🍒', 'Cherry', '车厘子', false, 'yingtao', 'Y'),
('lychee', '荔枝', '新鲜水果', '🫒', 'Lychee', '', false, 'lizhi', 'L'),
('grape', '青提', '新鲜水果', '🍇', 'Green Grape', '', false, 'qingti', 'Q'),
('yuzu', '柚子 / 柚子汁', '新鲜水果', '🍈', 'Yuzu', '', false, 'youziyouzizhi', 'Y'),
('longan', '桂圆（龙眼）', '新鲜水果', '🟤', 'Longan', '', false, 'guiyuanlongyan', 'G'),
('passionfruit', '百香果', '新鲜水果', '🟠', 'Passion Fruit', '', false, 'baixiangguo', 'B'),
('mango', '芒果', '新鲜水果', '🥭', 'Mango', '', false, 'mangguo', 'M'),
('watermelon', '西瓜', '新鲜水果', '🍉', 'Watermelon', '', false, 'xigua', 'X'),
('apple', '苹果', '新鲜水果', '🍎', 'Apple', '', false, 'pingguo', 'P'),
('peach-fruit', '桃子', '新鲜水果', '🍑', 'Peach', '', false, 'taozi', 'T'),
('pear', '梨', '新鲜水果', '🍐', 'Pear', '', false, 'li', 'L'),
('blueberry', '蓝莓', '新鲜水果', '🫐', 'Blueberry', '', false, 'lanmei', 'L'),
('raspberry', '覆盆子', '新鲜水果', '🍓', 'Raspberry', '', false, 'fupenzi', 'F'),
('blackberry', '黑莓', '新鲜水果', '🫐', 'Blackberry', '', false, 'heimei', 'H'),
('fig', '无花果', '新鲜水果', '🍈', 'Fig', '', false, 'wuhuaguo', 'W'),
('guava', '番石榴', '新鲜水果', '🍐', 'Guava', '', false, 'fanshiliu', 'F'),
('kiwi', '猕猴桃', '新鲜水果', '🥝', 'Kiwi', '', false, 'mihoutao', 'M'),
('hawthorn', '山楂', '新鲜水果', '🔴', 'Hawthorn', '', false, 'shanzha', 'S'),
('goji', '枸杞', '新鲜水果', '🔴', 'Goji Berry', '', false, 'gouqi', 'G'),
('plum', '青梅 / 话梅', '新鲜水果', '🟢', 'Green Plum', '', false, 'qingmeihuamei', 'Q'),
('pomegranate', '石榴', '新鲜水果', '🔴', 'Pomegranate', '', false, 'shiliu', 'S'),
('grape-red', '葡萄', '新鲜水果', '🍇', 'Grape / 巨峰', '', false, 'putao', 'P'),
('banana', '香蕉', '新鲜水果', '🍌', 'Banana', '', false, 'xiangjiao', 'X'),
('mint', '薄荷', '香草与装饰', '🌿', 'Mint', '薄荷叶', false, 'bohe', 'B'),
('basil', '罗勒', '香草与装饰', '🍃', 'Basil', '', false, 'luole', 'L'),
('rosemary', '迷迭香', '香草与装饰', '🌲', 'Rosemary', '', false, 'midiexiang', 'M'),
('cucumber', '黄瓜', '香草与装饰', '🥒', 'Cucumber', '小黄瓜', false, 'huanggua', 'H'),
('ginger', '生姜', '香草与装饰', '🫚', 'Ginger', '', false, 'shengjiang', 'S'),
('olive', '橄榄', '香草与装饰', '🫒', 'Olive', '', false, 'ganlan', 'G'),
('celery', '西芹', '香草与装饰', '🥬', 'Celery', '', false, 'xiqin', 'X'),
('osmanthus', '桂花', '香草与装饰', '🌼', 'Osmanthus', '', false, 'guihua', 'G'),
('matcha', '抹茶粉', '香草与装饰', '🍵', 'Matcha', '', false, 'mochafen', 'M'),
('coffee-bean', '咖啡豆', '香草与装饰', '🫘', 'Coffee Bean', '', false, 'kafeidou', 'K'),
('lemon-grass', '柠檬草', '香草与装饰', '🌾', 'Lemongrass', '', false, 'ningmengcao', 'N'),
('shiso', '紫苏叶', '香草与装饰', '🍃', 'Shiso', '', false, 'zisuye', 'Z'),
('thyme', '百里香', '香草与装饰', '🌿', 'Thyme', '', false, 'bailixiang', 'B'),
('sage', '鼠尾草', '香草与装饰', '🌿', 'Sage', '', false, 'shuweicao', 'S'),
('cilantro', '香菜', '香草与装饰', '🌿', 'Cilantro', '', false, 'xiangcai', 'X'),
('star-anise', '八角', '香草与装饰', '⭐', 'Star Anise', '', false, 'bajiao', 'B'),
('cinnamon-stick', '肉桂棒', '香草与装饰', '🪵', 'Cinnamon Stick', '', false, 'rouguibang', 'R'),
('edible-flower', '食用花瓣', '香草与装饰', '🌺', 'Edible Flower', '', false, 'shiyonghuaban', 'S'),
('pearl-onion', '珍珠洋葱', '香草与装饰', '🧅', 'Pearl Onion / Cocktail Onion', '鸡尾酒洋葱 / 腌洋葱', false, 'zhenzhuyangcong', 'Z'),
('ice', '冰块', '其他', '🧊', 'Ice', '', true, 'bingkuai', 'B'),
('nutmeg', '肉豆蔻', '其他', '🥜', 'Nutmeg', '', false, 'roudoukou', 'R')
on conflict (id) do nothing;
