-- 08-recipes-3.sql
-- 第二批经典鸡尾酒（29 款）同步到云数据库。可重复执行，已存在的会跳过。
-- 在「云开发控制台 → SQL 型数据库 → SQL 编辑器」整段粘贴执行。

-- 新增材料：热水（热托蒂等热饮要用）
insert into ingredients (id, name, cat, emoji, aka, alias, is_basic, py, initial) values
  ('hot-water', '热水', '其他', '♨️', 'Hot Water', '', false, 'reshui', 'R')
on conflict (id) do nothing;

-- 新增 29 款经典配方
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'brooklyn', '布鲁克林', 'Brooklyn', '', 'classic', '🌉', '#c96b4a', '马天尼杯', '高', '曼哈顿的「兄弟版」，把甜味美思换成干味美思，再加一点黑樱桃酒，喝起来更冷峻。', '', '', '', '["苦","草本","浓郁","短饮","烈","餐后"]'::jsonb, '[{"id":"rye","amount":"60 ml"},{"id":"dry-vermouth","amount":"20 ml"},{"id":"maraschino","amount":"10 ml"},{"id":"angostura","amount":"1 dash"}]'::jsonb, '["材料加冰搅拌 20 秒","滤入冰镇马天尼杯","樱桃或柠檬皮装饰"]'::jsonb, 'bulukelin', 'B', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'bijou', '珠宝', 'Bijou', '', 'classic', '💎', '#d9b45a', '马天尼杯', '高', '19 世纪末的经典，金酒 + 甜味美思 + 荨麻酒，名字取自三种酒的颜色像三颗宝石。', '', '', '', '["甜","草本","浓郁","短饮","烈","餐后"]'::jsonb, '[{"id":"gin","amount":"45 ml"},{"id":"sweet-vermouth","amount":"20 ml"},{"id":"chartreuse","amount":"15 ml"},{"id":"orange-bitters","amount":"1 dash"}]'::jsonb, '["材料加冰搅拌 20 秒","滤入冰镇马天尼杯","柠檬皮挤香后放入杯中"]'::jsonb, 'zhubao', 'Z', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'dirty-martini', '脏马天尼', 'Dirty Martini', '', 'classic', '🫒', '#b8b09a', '马天尼杯', '高', '在马天尼里加一勺腌橄榄的盐水，酒体会变浑浊（所以叫「脏」），咸香很上头。', '', '', '', '["咸","草本","清爽","短饮","烈","餐前"]'::jsonb, '[{"id":"gin","amount":"60 ml"},{"id":"dry-vermouth","amount":"10 ml"},{"id":"olive","amount":"2 颗"},{"id":"salt","amount":"少许"}]'::jsonb, '["材料加冰搅拌 20 秒","连一勺腌橄榄的盐水一起滤入冰镇马天尼杯","放两颗橄榄装饰"]'::jsonb, 'zangmatianni', 'Z', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'vodka-martini', '伏特加马天尼', 'Vodka Martini', '', 'classic', '🍸', '#dcd8cc', '马天尼杯', '高', '把金酒换成伏特加，杜松子香没了，口感更干净，007 点的那杯就是它。', '', '', '', '["清爽","短饮","烈","餐前"]'::jsonb, '[{"id":"vodka","amount":"60 ml"},{"id":"dry-vermouth","amount":"10 ml"},{"id":"lemon","amount":"1 片皮","optional":true}]'::jsonb, '["材料加冰搅拌 20 秒","滤入冰镇马天尼杯","柠檬皮挤香后装饰"]'::jsonb, 'futejiamatianni', 'F', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'death-in-the-afternoon', '午后之死', 'Death in the Afternoon', '', 'classic', '💀', '#e7d98a', '香槟杯', '高', '海明威自己发明的：苦艾酒加香槟。倒进去会变成乳白色，也叫「海明威效应」。', '', '', '', '["草本","气泡","短饮","烈","餐后"]'::jsonb, '[{"id":"absinthe","amount":"15 ml"},{"id":"sparkling","amount":"90 ml"}]'::jsonb, '["香槟杯中先倒入苦艾酒","缓慢注入冰镇起泡酒","看着它变成乳白色，轻轻搅一下"]'::jsonb, 'wuhouzhisi', 'W', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'boston-sour', '波士顿酸', 'Boston Sour', '', 'classic', '🍋', '#e8c98a', '古典杯', '中', '威士忌酸加蛋白，摇出绵密的奶盖感，是酸酒家族里最讨喜的一支。', '', '', '', '["酸","绵密","奶香","短饮","中等","餐后"]'::jsonb, '[{"id":"bourbon","amount":"50 ml"},{"id":"lemon-juice","amount":"20 ml"},{"id":"simple-syrup","amount":"15 ml"},{"id":"egg-white","amount":"1 个"},{"id":"angostura","amount":"1 dash","optional":true}]'::jsonb, '["除苦精外全部材料加冰大力摇 12 秒","滤掉冰再干摇一次，让蛋白起泡","滤入放冰的古典杯","表面滴两滴苦精"]'::jsonb, 'boshidunsuan', 'B', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'bahama-mama', '巴哈马妈妈', 'Bahama Mama', '', 'classic', '🌴', '#e07a3a', '高球杯', '中', '热带派对的常客，朗姆 + 椰香 + 两种果汁，甜得像在度假。', '', '', '', '["甜","果香","长饮","中等","夏日","派对"]'::jsonb, '[{"id":"dark-rum","amount":"30 ml"},{"id":"malibu","amount":"20 ml"},{"id":"pineapple-juice","amount":"60 ml"},{"id":"orange-juice","amount":"30 ml"},{"id":"grenadine","amount":"10 ml"},{"id":"ice","amount":"满杯"}]'::jsonb, '["全部材料加冰摇匀","滤入放冰的高球杯","菠萝片与樱桃装饰"]'::jsonb, 'bahamama', 'B', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'caipirissima', '卡琵莉西玛', 'Caipirissima', '', 'classic', '🍈', '#a8d98a', '古典杯', '中', '卡琵利亚的朗姆版本，做法一模一样，把甘蔗酒换成白朗姆就好。', '', '', '', '["酸","甜","清爽","短饮","中等","夏日"]'::jsonb, '[{"id":"white-rum","amount":"60 ml"},{"id":"lime","amount":"1 个"},{"id":"sugar","amount":"2 茶匙"},{"id":"ice","amount":"碎冰满杯"}]'::jsonb, '["青柠切块，与糖一起轻捣出汁","加入白朗姆与碎冰","搅拌至杯壁结霜"]'::jsonb, 'kapilixima', 'K', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'algonquin', '阿尔冈琴', 'Algonquin', '', 'classic', '🖋️', '#d9a441', '马天尼杯', '高', '纽约阿尔冈琴酒店的老配方，黑麦威士忌配菠萝汁，酸得意外地协调。', '', '', '', '["酸","果香","清爽","短饮","烈","餐前"]'::jsonb, '[{"id":"rye","amount":"45 ml"},{"id":"dry-vermouth","amount":"15 ml"},{"id":"pineapple-juice","amount":"15 ml"}]'::jsonb, '["材料加冰摇匀","滤入冰镇马天尼杯","不加装饰，直接喝"]'::jsonb, 'aergangqin', 'A', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'affinity', '亲和', 'Affinity', '', 'classic', '🤝', '#b5763a', '马天尼杯', '高', '苏格兰威士忌配两种味美思，烟熏与草本互相衬托，适合慢慢喝。', '', '', '', '["苦","草本","浓郁","短饮","烈","餐后"]'::jsonb, '[{"id":"scotch","amount":"40 ml"},{"id":"sweet-vermouth","amount":"20 ml"},{"id":"dry-vermouth","amount":"20 ml"},{"id":"orange-bitters","amount":"2 dash"}]'::jsonb, '["材料加冰搅拌 20 秒","滤入冰镇马天尼杯","橙皮装饰"]'::jsonb, 'qinhe', 'Q', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'casino', '卡西诺', 'Casino', '', 'classic', '🎲', '#e8d98a', '马天尼杯', '中', '金酒 + 黑樱桃酒 + 柠檬，酸甜干净，名字来自摩纳哥的赌场。', '', '', '', '["酸","甜","果香","短饮","中等","餐前"]'::jsonb, '[{"id":"gin","amount":"45 ml"},{"id":"maraschino","amount":"10 ml"},{"id":"lemon-juice","amount":"10 ml"},{"id":"orange-bitters","amount":"2 dash"}]'::jsonb, '["材料加冰摇匀","滤入冰镇马天尼杯","樱桃装饰"]'::jsonb, 'kaxinuo', 'K', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'tuxedo', '燕尾服', 'Tuxedo', '', 'classic', '🎩', '#c9c2a8', '马天尼杯', '高', '19 世纪绅士俱乐部里的马天尼变体，加一点黑樱桃酒和苦艾酒，香气更立体。', '', '', '', '["草本","清爽","短饮","烈","餐前"]'::jsonb, '[{"id":"gin","amount":"45 ml"},{"id":"dry-vermouth","amount":"15 ml"},{"id":"maraschino","amount":"5 ml"},{"id":"absinthe","amount":"1 dash"},{"id":"orange-bitters","amount":"1 dash"}]'::jsonb, '["材料加冰搅拌 20 秒","滤入冰镇马天尼杯","樱桃与柠檬皮装饰"]'::jsonb, 'yanweifu', 'Y', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'mary-pickford', '玛丽·皮克馥', 'Mary Pickford', '', 'classic', '🎬', '#f2a0a0', '马天尼杯', '中', '哈瓦那的黄金年代为默片女星玛丽·皮克馥调的，菠萝与石榴的粉红色很讨喜。', '', '', '', '["甜","果香","清爽","短饮","中等","餐前"]'::jsonb, '[{"id":"white-rum","amount":"45 ml"},{"id":"pineapple-juice","amount":"45 ml"},{"id":"grenadine","amount":"10 ml"},{"id":"maraschino","amount":"5 ml"}]'::jsonb, '["材料加冰摇匀","滤入冰镇马天尼杯","樱桃装饰"]'::jsonb, 'malipikefu', 'M', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'old-cuban', '老古巴', 'Old Cuban', '', 'classic', '💃', '#d9a441', '香槟杯', '中', '2000 年代纽约的创作，本质是「加了香槟的莫吉托」，薄荷 + 起泡酒很清爽。', '', '', '', '["酸","果香","气泡","草本","长饮","中等","夏日"]'::jsonb, '[{"id":"aged-rum","amount":"45 ml"},{"id":"lime-juice","amount":"15 ml"},{"id":"simple-syrup","amount":"15 ml"},{"id":"mint","amount":"6 片"},{"id":"angostura","amount":"2 dash"},{"id":"sparkling","amount":"60 ml"}]'::jsonb, '["薄荷与糖浆在雪克杯里轻压出香","加入朗姆、青柠汁与苦精，加冰摇匀","滤入香槟杯","起泡酒补满，插薄荷尖"]'::jsonb, 'laoguba', 'L', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'pegu-club', '佩古俱乐部', 'Pegu Club', '', 'classic', '🐯', '#e0a94a', '马天尼杯', '中', '缅甸仰光的英国俱乐部配方，金酒 + 橙酒 + 青柠 + 双份苦精，结构非常工整。', '', '', '', '["酸","苦","果香","短饮","中等","餐前"]'::jsonb, '[{"id":"gin","amount":"45 ml"},{"id":"cointreau","amount":"15 ml"},{"id":"lime-juice","amount":"15 ml"},{"id":"angostura","amount":"1 dash"},{"id":"orange-bitters","amount":"1 dash"}]'::jsonb, '["材料加冰摇匀","滤入冰镇马天尼杯","青柠皮装饰"]'::jsonb, 'peigujulebu', 'P', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'pink-gin', '粉红金酒', 'Pink Gin', '', 'classic', '🌸', '#f0a8b8', '马天尼杯', '高', '英国海军的喝法：苦精洗杯，再倒冰金酒。两样材料，颜色很漂亮。', '', '', '', '["苦","草本","短饮","烈","餐前"]'::jsonb, '[{"id":"gin","amount":"60 ml"},{"id":"angostura","amount":"3 dash"},{"id":"ice","amount":"适量"}]'::jsonb, '["冰镇马天尼杯里滴入苦精，转动杯子让酒液挂壁","倒入冰镇金酒","把浮在表面的苦精撇掉即可"]'::jsonb, 'fenhongjinjiu', 'F', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'salty-dog', '咸狗', 'Salty Dog', '', 'classic', '🐕', '#f2c8a0', '高球杯', '中', '灰狗的盐边版本，盐把西柚的苦甜压得更清楚。', '', '', '', '["酸","咸","清爽","长饮","中等","夏日"]'::jsonb, '[{"id":"vodka","amount":"45 ml"},{"id":"grapefruit-juice","amount":"90 ml"},{"id":"salt","amount":"少许"},{"id":"ice","amount":"满杯"}]'::jsonb, '["用柠檬角擦湿杯口，蘸一圈盐","杯中加冰，倒入伏特加与西柚汁","轻轻搅拌两下"]'::jsonb, 'xiangou', 'X', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'frozen-daiquiri', '冰冻代基里', 'Frozen Daiquiri', '', 'classic', '🧊', '#cfe8e0', '大杯', '中', '把代基里打成冰沙，夏天最没有抵抗力的一杯。', '', '', '', '["酸","甜","冰沙","清爽","短饮","中等","夏日"]'::jsonb, '[{"id":"white-rum","amount":"60 ml"},{"id":"lime-juice","amount":"25 ml"},{"id":"simple-syrup","amount":"15 ml"},{"id":"ice","amount":"一杯"}]'::jsonb, '["所有材料加碎冰打成沙","倒入冰镇大杯","青柠片装饰，配吸管"]'::jsonb, 'bingdongdaijili', 'B', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'rum-runner', '朗姆走私者', 'Rum Runner', '', 'classic', '🏴‍☠️', '#e05a4a', '高球杯', '中', '佛罗里达的度假名酒，香蕉利口酒 + 黑莓利口酒，颜色和味道都很热闹。', '', '', '', '["甜","果香","长饮","中等","夏日","派对"]'::jsonb, '[{"id":"dark-rum","amount":"30 ml"},{"id":"banana-liqueur","amount":"15 ml"},{"id":"creme-de-cassis","amount":"10 ml"},{"id":"pineapple-juice","amount":"45 ml"},{"id":"grenadine","amount":"10 ml"},{"id":"lime-juice","amount":"10 ml"}]'::jsonb, '["全部材料加冰摇匀","滤入放冰的高球杯","菠萝片与樱桃装饰"]'::jsonb, 'langmuzousizhe', 'L', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'yellow-bird', '黄鸟', 'Yellow Bird', '', 'classic', '🐤', '#f2d05a', '马天尼杯', '中', '加勒比经典，加利安奴的香草甜配上朗姆和青柠，颜色像热带的小鸟。', '', '', '', '["甜","酸","果香","短饮","中等","夏日"]'::jsonb, '[{"id":"white-rum","amount":"30 ml"},{"id":"galliano","amount":"15 ml"},{"id":"triple-sec","amount":"15 ml"},{"id":"lime-juice","amount":"15 ml"}]'::jsonb, '["材料加冰摇匀","滤入冰镇马天尼杯","樱桃装饰"]'::jsonb, 'huangniao', 'H', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'hot-toddy', '热托蒂', 'Hot Toddy', '', 'classic', '☕', '#c98a4a', '马克杯', '中', '感冒时的老偏方，威士忌 + 蜂蜜 + 柠檬 + 热水，捧在手里就很舒服。', '', '', '', '["甜","酸","草本","长饮","中等","冬日"]'::jsonb, '[{"id":"scotch","amount":"45 ml"},{"id":"honey","amount":"15 ml"},{"id":"lemon-juice","amount":"15 ml"},{"id":"hot-water","amount":"90 ml"},{"id":"clove","amount":"2 颗","optional":true},{"id":"cinnamon-stick","amount":"1 根","optional":true}]'::jsonb, '["杯中放蜂蜜与柠檬汁","倒入威士忌搅匀","注入热水，放肉桂棒与丁香","趁热喝"]'::jsonb, 'retuodi', 'R', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'mulled-wine', '热红酒', 'Mulled Wine', '', 'classic', '🍷', '#a8503a', '马克杯', '低', '圣诞集市的香气：红酒加橙子和香料微微加热，注意千万别煮沸。', '', '', '', '["甜","果香","长饮","微醺","冬日","派对"]'::jsonb, '[{"id":"red-wine","amount":"200 ml"},{"id":"orange","amount":"1 个"},{"id":"honey","amount":"30 ml"},{"id":"cinnamon-stick","amount":"1 根"},{"id":"clove","amount":"5 颗"},{"id":"star-anise","amount":"2 颗"}]'::jsonb, '["橙子切片，与红酒、香料一起小火加热至微微冒热气","关火前加蜂蜜调味，不要煮沸","焖 10 分钟后滤入杯中"]'::jsonb, 'rehongjiu', 'R', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'red-snapper', '红鲷鱼', 'Red Snapper', '', 'classic', '🐟', '#d94a3a', '高球杯', '低', '血腥玛丽的琴酒版本——其实比原版更早，用金酒配番茄汁和香料。', '', '', '', '["咸","酸","清爽","长饮","微醺","餐前"]'::jsonb, '[{"id":"gin","amount":"45 ml"},{"id":"tomato-juice","amount":"120 ml"},{"id":"lemon-juice","amount":"15 ml"},{"id":"worcestershire","amount":"3 滴"},{"id":"tabasco","amount":"2 滴"},{"id":"celery-salt","amount":"少许"},{"id":"pepper","amount":"少许"}]'::jsonb, '["全部材料倒入调酒杯，加冰来回滚动混合","滤入放冰的高球杯","芹菜杆与柠檬角装饰"]'::jsonb, 'hongdiaoyu', 'H', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'tequila-sour', '龙舌兰酸', 'Tequila Sour', '', 'classic', '🌵', '#d9e08a', '古典杯', '中', '龙舌兰的植物感配上蛋白，酸酒里最有「人味」的一杯。', '', '', '', '["酸","绵密","清爽","短饮","中等","餐前"]'::jsonb, '[{"id":"tequila","amount":"50 ml"},{"id":"lemon-juice","amount":"20 ml"},{"id":"simple-syrup","amount":"15 ml"},{"id":"egg-white","amount":"1 个"},{"id":"angostura","amount":"1 dash","optional":true}]'::jsonb, '["除苦精外加冰大力摇 12 秒","滤掉冰再干摇起泡","滤入放冰的古典杯，表面滴苦精"]'::jsonb, 'longsheliansuan', 'L', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'b-53', 'B-53 轰炸机', 'B-53', '', 'classic', '🎯', '#4a3a2a', '子弹杯', '高', '三层分层的经典小杯，一层咖啡、一层奶酒、一层苦艾，一口下去。', '', '', '', '["甜","奶香","短饮","烈","餐后","派对"]'::jsonb, '[{"id":"kahlua","amount":"20 ml"},{"id":"baileys","amount":"20 ml"},{"id":"absinthe","amount":"20 ml"}]'::jsonb, '["子弹杯中先倒咖啡利口酒","沿匙背缓慢倒入奶酒，形成第二层","再沿匙背倒苦艾酒，分层明显即可"]'::jsonb, 'b53hongzhaji', 'B', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'french-martini', '法兰西马天尼', 'French Martini', '', 'classic', '🇫🇷', '#d95a8a', '马天尼杯', '中', '90 年代纽约的爆款，伏特加 + 黑莓利口酒 + 菠萝汁，摇出来带一层细泡沫。', '', '', '', '["甜","果香","绵密","短饮","中等","派对"]'::jsonb, '[{"id":"vodka","amount":"45 ml"},{"id":"chambord","amount":"15 ml"},{"id":"pineapple-juice","amount":"45 ml"}]'::jsonb, '["材料加冰大力摇匀","滤入冰镇马天尼杯","菠萝叶或柠檬皮装饰"]'::jsonb, 'falaximatianni', 'F', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'pornstar-martini', '明星马天尼', 'Pornstar Martini', '', 'classic', '⭐', '#f2c05a', '马天尼杯', '中', '百香果风味的现代经典，旁边配一小杯起泡酒，一口酒一口香槟交替喝。', '', '', '', '["甜","酸","果香","气泡","短饮","中等","夏日","派对"]'::jsonb, '[{"id":"vodka","amount":"40 ml"},{"id":"passionfruit-syrup","amount":"20 ml"},{"id":"passionfruit","amount":"1 个"},{"id":"lime-juice","amount":"10 ml"},{"id":"sparkling","amount":"60 ml"}]'::jsonb, '["百香果对半切开，取一半果肉入杯","加伏特加、百香果糖浆与青柠汁，加冰摇匀","滤入冰镇马天尼杯，放半颗百香果","另配一小杯冰起泡酒一起上"]'::jsonb, 'mingxingmatianni', 'M', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'miami-vice', '迈阿密风云', 'Miami Vice', '', 'classic', '🍹', '#f2a0a0', '高球杯', '中', '80 年代的产物：一半椰香朗姆冰沙，一半草莓冰沙，同时倒进杯子就有了分层。', '', '', '', '["甜","果香","冰沙","长饮","中等","夏日","派对"]'::jsonb, '[{"id":"white-rum","amount":"30 ml"},{"id":"malibu","amount":"15 ml"},{"id":"pineapple-juice","amount":"45 ml"},{"id":"strawberry","amount":"3 颗"},{"id":"lime-juice","amount":"10 ml"},{"id":"ice","amount":"两杯"}]'::jsonb, '["朗姆、椰香酒、菠萝汁加冰打成椰香冰沙","另一份加草莓与青柠汁打成草莓冰沙","两种冰沙同时从两侧倒入杯中形成分层","菠萝片与草莓装饰"]'::jsonb, 'maiamifengyun', 'M', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;
insert into recipes (id, name, en, alias, type, emoji, color, glass, abv, "desc", image, video, video_name, tags, items, steps, py, initial, author_id, author, status, views, created_at) values (
  'sangria', '桑格利亚', 'Sangria', '', 'classic', '🍇', '#a83a4a', '大杯', '低', '西班牙的水果红酒，提前泡一大壶，聚会时最省事也最受欢迎。', '', '', '', '["甜","果香","清爽","长饮","微醺","夏日","派对"]'::jsonb, '[{"id":"red-wine","amount":"300 ml"},{"id":"orange","amount":"1 个"},{"id":"apple","amount":"1 个"},{"id":"lemon","amount":"半个"},{"id":"brandy","amount":"30 ml"},{"id":"sugar","amount":"2 茶匙"},{"id":"sparkling-water","amount":"适量","optional":true}]'::jsonb, '["橙子、苹果、柠檬切块放入壶中","倒入红酒、白兰地与糖拌匀","冷藏浸泡 2 小时以上","喝时倒进放冰的大杯，可加一点气泡水"]'::jsonb, 'sangeliya', 'S', 'u-admin', '官方', 'approved', 0, now())
on conflict (id) do nothing;

-- 看看现在有多少款配方（应该是 144）
select count(*) as 配方数 from recipes;
